/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PIN0.h"
#include "PIN0_aliases.h"
#include "PIN1.h"
#include "PIN1_aliases.h"
#include "PIN2.h"
#include "PIN2_aliases.h"
#include "Control_PIN1.h"
#include "PIN3.h"
#include "PIN3_aliases.h"
#include "PIN7.h"
#include "PIN7_aliases.h"
#include "PIN6.h"
#include "PIN6_aliases.h"
#include "PIN5.h"
#include "PIN5_aliases.h"
#include "PIN4.h"
#include "PIN4_aliases.h"
#include "UART.h"
#include "UART_I2C.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_I2C_PVT.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_EZI2C.h"
#include "UART_EZI2C_PVT.h"
#include "UART_BOOT.h"
#include "UARTclock.h"
#include "UART_uart_rx_i2c_scl_spi_mosi.h"
#include "UART_uart_rx_i2c_scl_spi_mosi_aliases.h"
#include "UART_uart_tx_i2c_sda_spi_miso.h"
#include "UART_uart_tx_i2c_sda_spi_miso_aliases.h"
#include "UART_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

