#include "PIN0.h"
#include "PIN1.h"
#include "PIN2.h"
#include "PIN3.h"
#include "PIN4.h"
#include "PIN5.h"
#include "PIN6.h"
#include "PIN7.h"
#include "UARTclock.h"
#include "UART_SPI_UART.h"
#include "Cylib.h"
#include <core_cm0_psoc4.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>
